<?php

declare(strict_types=1);

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Symfony\Component\Yaml\Yaml;

/**
 * docs/api.html has to work from file://, where a browser will not fetch
 * docs/openapi.yaml. So the spec is also shipped as a tiny JavaScript file
 * that assigns the YAML text to window.OPENAPI_YAML, and the page loads that
 * with a <script> tag instead of fetching. This command regenerates the
 * wrapper; OpenApiSpecTest fails when it is out of date.
 */
class EmbedOpenApi extends Command
{
    protected $signature = 'platform:embed-openapi';

    protected $description = 'Regenerate docs/openapi.yaml.js from docs/openapi.yaml for the offline viewer';

    public const YAML = 'docs/openapi.yaml';

    public const EMBED = 'docs/openapi.yaml.js';

    public function handle(): int
    {
        $yaml = file_get_contents(base_path(self::YAML));

        if ($yaml === false) {
            $this->error(self::YAML.' is missing.');

            return self::FAILURE;
        }

        // Fail here rather than in a browser console.
        Yaml::parse($yaml);

        file_put_contents(base_path(self::EMBED), self::wrap($yaml));
        $this->info('Wrote '.self::EMBED.' ('.number_format(strlen($yaml)).' bytes of YAML).');

        return self::SUCCESS;
    }

    /** The exact file contents the viewer expects, so the test can compare byte for byte. */
    public static function wrap(string $yaml): string
    {
        return "// Generated by `php artisan platform:embed-openapi` from docs/openapi.yaml. Do not edit.\n"
            .'window.OPENAPI_YAML = '.json_encode($yaml, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE).";\n";
    }
}
